import { COIN_RULES, DAILY_COIN_CAP, GOAL_TARGET_COINS, STREAK_MILESTONES, XP_RULES } from "@/lib/economy";

/** Single source of truth the AXEN Coach uses to explain every feature. Built from live constants. */
export function buildCoachKnowledge(): string {
  const df = Object.entries(COIN_RULES.deepFocus).map(([k, v]) => `${k} = ${v} coins`).join(", ");
  const ms = STREAK_MILESTONES.map(m => `${m.days} days → ${m.coins.toLocaleString()} coins (${m.tone === "diamond" ? "dark-blue diamond" : m.tone} badge)`).join("; ");
  return `AXEN APP KNOWLEDGE (accurate; explain simply, say WHY each feature exists):
- HOME: today's habits, Deep Focus, Today's Contract card, Top 3 Missions, Focus Music. Completing any habit keeps your daily streak alive (streak = consecutive days with at least one completion). Why: one screen for today's real actions.
- COINS: server-awarded only, never by the app on your phone. Contract verified ${COIN_RULES.contractVerified}; recovery contract ${COIN_RULES.contractRecovery}; Deep Focus ${df}; Wake Up 4AM selfie ${COIN_RULES.wakeSelfie}; priority habit tick (Cold Shower, Workout) ${COIN_RULES.priorityHabit}; custom habit ${COIN_RULES.customHabit.min}-${COIN_RULES.customHabit.max}; Zen ${COIN_RULES.zen}; Top 3 Missions ${COIN_RULES.top3.join("+")}; Focus Music ${COIN_RULES.focusMusic} (focus only). Maximum ${DAILY_COIN_CAP} coins per day in total (streak milestone bonuses are separate). Why: verified effort pays most, easy taps pay little. Coins unlock ranks, themes and goal progress.
- XP & RANK: XP comes from your coin balance and verified actions and decides your rank tier and leaderboard place. ${XP_RULES.map(r => `${r.title} ${r.xp}`).join(", ")}. Contracts give ${COIN_RULES.contractXp} XP (recovery ${COIN_RULES.recoveryXp} XP). XP can never be bought. Rank tab: rank tiers, rewards/themes, leaderboard, info dot explaining XP.
- STREAK MILESTONES (Stats): ${ms}. Each pays once when your streak reaches that many days; the earned badge then shows permanently next to your name on Profile and Rank.
- STATS: Focus Time (Deep Focus minutes vs 5h weekly), Mindful Habits (active days), Meditation Consistency, Discipline Score (weekly completion %), weekly chart, streak milestones.
- ZEN: guided meditation/breathing; a finished session (5+ min) gives ${COIN_RULES.zen} coins. Why: calm mind = better discipline.
- COACH: you (text and voice). You use the user's live data, never invent numbers, and give one clear next action.
- YOU/PROFILE: name, streak badge, rank, habits, goals, reminders, accountability, account and subscription settings.
- GOALS: create a goal, link habits. Progress = coins earned from linked habits since the goal started ÷ ${GOAL_TARGET_COINS.toLocaleString()}; the bar fills gradually and hits 100% only at ${GOAL_TARGET_COINS.toLocaleString()}. Info promise: reaching ${GOAL_TARGET_COINS.toLocaleString()} coins is your proof of work — consistency compounds (a motivational promise, not a guarantee).
- BUILD YOUR DISCIPLINE (habits): priority habits Wake Up 4AM, Cold Shower, Workout. Wake Up 4AM is verified by a live front-camera selfie only between 4:00 and 4:30 AM local time; the photo is checked and deleted instantly, never stored or shown. Cold Shower and Workout are simple taps. Build Any Habit: name, frequency (daily/weekdays/weekends/weekly), duration (21/30/60/90 days), reward ${COIN_RULES.customHabit.min}-${COIN_RULES.customHabit.max} coins; no scan proof.
- DEEP FOCUS: full-screen focus timer (49 min / 2 h / 3 h), paid AXEN Pro only, with focus sounds and an Emergency Exit. It does not block other apps.
- TODAY'S CONTRACT: a specific promise for today (title, time, duration, proof method, optional goal). Flow: create → scheduled → START CONTRACT opens a focus session → timer completes → submit proof (timer, recall, checklist, photo or Zen) → server verifies → CLAIM REWARD (${COIN_RULES.contractXp} XP + ${COIN_RULES.contractVerified} coins, once). Reminders 5 min before and at start. If missed: same-day recovery — a rescue version (20% of the time, min 5 min) ending at local midnight, reward ${COIN_RULES.recoveryXp} XP + ${COIN_RULES.contractRecovery} coins, badge "Recovered". One recovery per contract. Why: a concrete commitment beats vague intentions.
- ACCOUNTABILITY: one partner. Create a one-time invite code (24h) in You → Accountability, partner enters it. Each side can share contract progress (partner sees only today's title and status — never notes, photos, coins, XP or history), send fixed nudges ("You've got this", "Start now", "Great work", "Try the rescue version"; max 3 per contract, 10 per day), mute nudges, remove or block the partner anytime. Why: gentle social commitment without privacy loss.
- SOFT SHIELD: keep-screen-awake switch and a Do Not Disturb tip during contract focus. AXEN does not block other apps.
If asked about something not listed, say you are not sure rather than guessing.`;
}
