import { useEffect, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { askCoach, getLatestCoachConversation, type CoachMessage } from "@/utils/coach.functions";
import { haptic } from "@/lib/haptics";
import { ChevronUp, Clock3, Plus } from "lucide-react";
import { VoiceCoach } from "@/components/VoiceCoach";
import { Conversation,ConversationContent,ConversationScrollButton } from "@/components/ai-elements/conversation";
import { Message,MessageContent,MessageResponse } from "@/components/ai-elements/message";
import { PromptInput,PromptInputFooter,PromptInputSubmit,PromptInputTextarea } from "@/components/ai-elements/prompt-input";
import coachOffice from "@/assets/ai-coach-office.jpg";

const STARTERS=["Plan my next 7 days","Fix my weakest habit","I feel like quitting"];
export function AiCoach({onOpenFocus,onCreateHabit}:{onOpenFocus?:()=>void;onCreateHabit?:(name:string)=>void}){
  const ask=useServerFn(askCoach); const load=useServerFn(getLatestCoachConversation);
  const[messages,setMessages]=useState<CoachMessage[]>([]);const[conversationId,setConversationId]=useState<string|null>(null);const[input,setInput]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[chatOpen,setChatOpen]=useState(false);const[loaded,setLoaded]=useState(false);
  useEffect(()=>{let active=true;load().then(result=>{if(!active)return;setMessages(result.messages);setConversationId(result.conversationId);setChatOpen(result.messages.length>0);}).catch(()=>{}).finally(()=>active&&setLoaded(true));return()=>{active=false};},[load]);
  const send=async(text:string)=>{const q=text.trim();if(!q||busy)return;haptic("tap");setError(null);setInput("");setChatOpen(true);const next=[...messages,{role:"user" as const,content:q}];setMessages(next);setBusy(true);try{const result=await ask({data:{messages:next.slice(-12),conversationId}});setConversationId(result.conversationId);setMessages([...next,{role:"assistant",content:result.reply,suggestedAction:result.suggestedAction}]);haptic("success");}catch(cause){setError(cause instanceof Error?cause.message:"The coach could not answer right now.");}finally{setBusy(false);}};
  useEffect(()=>{const handler=(event:Event)=>{const question=(event as CustomEvent<{question?:string}>).detail?.question;if(question)void send(question);};window.addEventListener("axen:coach-question",handler);return()=>window.removeEventListener("axen:coach-question",handler);});
  const action=(item:CoachMessage)=>{if(item.suggestedAction?.type==="open_focus")onOpenFocus?.();if(item.suggestedAction?.type==="create_habit")onCreateHabit?.(item.suggestedAction.value??"Daily discipline habit");};
  return <section className="coach-stage" aria-label="AXEN AI Coach"><img src={coachOffice} alt="AXEN virtual discipline coach in a futuristic office" width={720} height={1280} className="coach-stage__portrait"/><div className="coach-stage__shade"/><div className="coach-stage__controls"><VoiceCoach/>{!chatOpen&&<div className="coach-stage__starters" aria-label="Suggested questions">{STARTERS.map(item=><button key={item} onClick={()=>send(item)} disabled={busy}>{item}</button>)}</div>}<div className={`coach-chat ${chatOpen?"coach-chat--open":""}`}><button className="coach-chat__handle" onClick={()=>setChatOpen(open=>!open)} aria-expanded={chatOpen}><ChevronUp size={16}/>{chatOpen?"Close text coach":"Open text coach"}</button>{chatOpen&&<div className="coach-chat__body"><Conversation className="coach-chat__conversation"><ConversationContent className="gap-4 px-3 py-3">{loaded&&messages.length===0&&<p className="coach-chat__empty">Ask for a plan, a reset, or one direct action for today.</p>}{messages.map((message,index)=><Message key={message.id??`${message.role}-${index}`} from={message.role}><MessageContent className={message.role==="user"?"coach-chat__user":"coach-chat__assistant"}><MessageResponse>{message.content}</MessageResponse></MessageContent>{message.suggestedAction&&<button className="coach-action" onClick={()=>action(message)}>{message.suggestedAction.type==="open_focus"?<Clock3 size={14}/>:<Plus size={14}/>} {message.suggestedAction.label}</button>}</Message>)}{busy&&<p className="coach-chat__thinking">Coach is thinking…</p>}{error&&<p className="coach-chat__error">{error}</p>}</ConversationContent><ConversationScrollButton/></Conversation><PromptInput className="coach-chat__composer" onSubmit={({text})=>send(text)}><PromptInputTextarea name="message" value={input} onChange={event=>setInput(event.target.value)} placeholder="Message your coach…" className="min-h-12 max-h-24"/><PromptInputFooter className="justify-end"><PromptInputSubmit status={busy?"submitted":"ready"} disabled={busy||!input.trim()}/></PromptInputFooter></PromptInput></div>}</div></div></section>;
}