import { useEffect, useState } from "react";
import { Check, Minus, ShieldCheck, Sparkles } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { PlatformCheckout } from "@/components/PlatformCheckout";
import { isNativeBillingAvailable } from "@/lib/play-billing";
import { PRICING, type Cycle } from "@/lib/pricing";

const FEATURES=[{name:"Daily habits, streaks and coins",basic:true},{name:"Up to 3 active reminders",basic:true},{name:"Stats and personal journey",basic:true},{name:"4AM Wake Verification",basic:false},{name:"AI discipline coach",basic:false},{name:"Zen, Rank and premium themes",basic:false},{name:"Unlimited reminders",basic:false}];
export function Paywall({userId,email}:{userId:string;email?:string|null}){
  const[cycle,setCycle]=useState<Cycle>("yearly");const[native,setNative]=useState(false);
  useEffect(()=>{isNativeBillingAvailable().then(setNative).catch(()=>setNative(false));},[]);
  return <main className="membership-screen"><header><div><Sparkles size={22}/></div><span>AXEN MEMBERSHIP</span><h1>Choose your discipline system</h1><p>Start with the essentials. Unlock the complete AXEN system when you are ready.</p></header>
    <div className="membership-plans"><section><span>BASIC</span><h2>Free</h2><p>Your daily discipline foundation.</p>{FEATURES.map(item=><div key={item.name} className={item.basic?"":"is-muted"}>{item.basic?<Check size={15}/>:<Minus size={15}/>}<span>{item.name}</span></div>)}</section><section className="is-pro"><span>AXEN PRO</span><h2>{PRICING[cycle].display}</h2><p>{PRICING[cycle].sub}</p>{FEATURES.map(item=><div key={item.name}><Check size={15}/><span>{item.name}</span></div>)}</section></div>
    <div className="membership-cycle">{(["monthly","yearly"] as const).map(item=><button key={item} className={cycle===item?"is-active":""} onClick={()=>setCycle(item)}><span>{item}</span><b>{PRICING[item].display}</b>{PRICING[item].save&&<small>{PRICING[item].save}</small>}</button>)}</div>
    <PlatformCheckout userId={userId} cycle={cycle} email={email}/>
    <p className="membership-note"><ShieldCheck size={14}/>{native?"Secure store billing. Cancel anytime in your store subscriptions.":"Purchases are completed securely inside the AXEN mobile app."}</p>
    <button className="membership-signout" onClick={()=>supabase.auth.signOut()}>Sign out</button>
  </main>;
}
export function PaywallLoading(){return <div className="membership-loading">Preparing AXEN…</div>}
type SubRow={status:string;current_period_end:string|null};
function isRowActive(row:SubRow){const end=row.current_period_end?new Date(row.current_period_end):null;const valid=!end||end>new Date();return (["active","past_due"].includes(row.status)&&valid)||(row.status==="canceled"&&!!end&&end>new Date());}
export function PaywallGate({children}:{children:React.ReactNode}){const[userId,setUserId]=useState<string|null>(null);const[email,setEmail]=useState<string|null>(null);const[ready,setReady]=useState(false);const[sub,setSub]=useState<SubRow|null>(null);const refresh=async(uid:string)=>{const{data}=await supabase.from("subscriptions").select("status,current_period_end").eq("user_id",uid).order("created_at",{ascending:false}).limit(20);const rows=(data??[]) as SubRow[];setSub(rows.find(isRowActive)??rows[0]??null);};useEffect(()=>{void(async()=>{const{data}=await supabase.auth.getUser();if(data.user){setUserId(data.user.id);setEmail(data.user.email??null);await refresh(data.user.id);if(await isNativeBillingAvailable().catch(()=>false)){try{const{initPlayBilling}=await import("@/lib/play-billing");const{syncPlayEntitlement}=await import("@/utils/play-billing.functions");await initPlayBilling(data.user.id);await syncPlayEntitlement({data:{}} as never);await refresh(data.user.id);}catch{}}}setReady(true);})();},[]);useEffect(()=>{if(!userId)return;const channel=supabase.channel(`gate_${userId}`).on("postgres_changes",{event:"*",schema:"public",table:"subscriptions",filter:`user_id=eq.${userId}`},()=>refresh(userId)).subscribe();const update=()=>refresh(userId);window.addEventListener("focus",update);window.addEventListener("subscription:refresh",update);return()=>{void supabase.removeChannel(channel);window.removeEventListener("focus",update);window.removeEventListener("subscription:refresh",update);};},[userId]);if(!ready||!userId)return<PaywallLoading/>;if(!sub||!isRowActive(sub))return<Paywall userId={userId} email={email}/>;return<>{children}</>}